name: Sanitize test

on: [push, pull_request]

jobs:
  sanitize:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Add LLVM to PATH (Windows)
        if: runner.os == 'Windows'
        run: echo "C:\Program Files\LLVM\bin" >> $GITHUB_PATH

      - name: Configure
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            export CC=clang
            export CXX=clang++
          fi

          cmake -B build-san -S . -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DENABLE_SANITIZERS=ON \
            -DBUILD_TESTS=ON

      - name: Build
        shell: bash
        run: cmake --build build-san

      - name: Run tests with sanitizers
        shell: bash
        run: ctest --test-dir build-san --output-on-failure
