name: Doxygen

permissions:
  contents: write

on:
  - push
  - pull_request

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v5

      - name: Install doxygen and graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate documentation
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          publish_branch: gh-pages
